#!/bin/bash
# manl 2019-08-13
# historically opened [man] pages in [l]eafpad

#=======================================================================================================
			# Setup manl editor
CLIeditor=nano
GUIeditor=leafpad
Editor="$(if [[ -z $DISPLAY ]]; then echo "$CLIeditor" ; else echo "$GUIeditor" ; fi)"

#=======================================================================================================
			# Print [-h --help] page

if	[[ -z ${1} ]] || [[ ${1} = -h ]] || [[ ${1} = --help ]]; then 

cat << 'EOF'

    manl opens man pages in your editor, prepended by either
    existing notes and/or makeing it easy to edit/create notes.

    Operations:
		-h --help  =  help page
		-Sn        =  Search for <manpage> numbers
		-St        =  Search manpages for <term> "man -k <term>"

    Usage   :  manl [operation] <manpage> -or-  manl <number manpage>
    Examples:  manl signal    -or-  manl 7 signal
               manl -Sn signal


    Notes automatically saved under  ~/.manl/<manpage "name"> or <manpage "number_name"]

    To save notes, just save in editor. It will create or edit ~/.manl/<manpage>.
    Manpage is automatically removed from notes after saving.
    No changes made to manpages (read only).

EOF
	exit
fi

#=======================================================================================================
			# Search Operations

if	[[ $1 = -Sn ]]; then 
	find /usr/share/man/man* | awk -v manp="${2}" -F / ' $0 ~ "/"manp {print $5 " " $6}'
    exit
fi

if	[[ $1 = -St ]]; then 
	man -k "${2}"			# man -wK "${2}" | awk -F / '{print $5 " " $6}'
    exit
fi

#=======================================================================================================
			# Prep existing notes + manpage for editor
			# else
			# Prep manpage for editor + potential note save
			# Add ability when "manpage unavailable", to open if present ~/.manl/<notes>. (For "notes title" symlinks.)

if	[[ -n ${2} ]] && [[ -e  ~/.manl/${1}_${2} ]]; then	### IF [NUMBER]_[MANPAGE] exists in ~/.manl
	cp ~/.manl/"${1}_${2}" /tmp/"${1}_${2}_"
	MANWIDTH=146 man "${1}" "${2}" >>/tmp/"${1}_${2}_"
    elif
	[[ -n ${2} ]]; then
	MANWIDTH=146 man "${1}" "${2}" >>/tmp/"${1}_${2}_" \
    ||	[[ -s ~/.manl/${1}_${2} ]] && "$Editor" ~/.manl/"${1}_${2}" ; exit || exit
fi


if	[[ -z ${2} ]] && [[ -e ~/.manl/${1} ]]; then		### IF (no number) [MANPAGE] exists in ~/.manl
	cp ~/.manl/"${1}" /tmp/"${1}_"
	MANWIDTH=146 man "${1}" >>/tmp/"${1}_"
    elif
	[[ -z ${2} ]]; then
	MANWIDTH=146 man "${1}" >>/tmp/"${1}_" \
    ||	[[ -s ~/.manl/${1} ]] && "$Editor" ~/.manl/"${1}" ; exit || exit
fi


#=======================================================================================================
			# Print manpage, or notes + manpage, in editor

if	[[ -n ${2} ]]; then					### IN EDITOR [NUMBER]_[MANPAGE]
	cp /tmp/"${1}_${2}_" ~/.manl/"${1}_${2}_"
	"$Editor" ~/.manl/"${1}_${2}_"

	tmpmd5=$(md5sum /tmp/"${1}_${2}_" | awk '{ print $1 }')
	manlmd5=$(md5sum ~/.manl/"${1}_${2}_" | awk '{ print $1 }')
	# echo "tmp  ${tmpmd5}"
	# echo "manl ${manlmd5}"
fi

if	[[ ${tmpmd5} != "${manlmd5}" ]]; then
	echo; echo "New notes saved as ~/.manl/${1}_${2}"

		if	[[ -e  ~/.manl/${1}_${2} ]]; then
			mv ~/.manl/"${1}_${2}" ~/.manl/"${1}_${2}.bu"
			echo; echo "Pre-edited notes saved as ~/.manl/${1}_${2}.bu" ; echo
		fi

	cp ~/.manl/"${1}_${2}_"  ~/.manl/"${1}_${2}"
	rm ~/.manl/"${1}_${2}_"
	rm /tmp/"${1}_${2}_"

	del=$(echo "${1}" | tr '[:lower:]' '[:upper:]')
	sed '/'"$del"'/,$d' ~/.manl/"${1}_${2}" > ~/.manl/"${1}_${2}".tmp
	mv ~/.manl/"${1}_${2}".tmp  ~/.manl/"${1}_${2}"
    elif
	[[ -n ${2} ]]; then
	rm ~/.manl/"${1}_${2}_"
	rm /tmp/"${1}_${2}_"
fi

if	[[ -z ${2} ]]; then					### IN EDITOR (no number) [MANPAGE]
	cp /tmp/"${1}_" ~/.manl/"${1}_"
	"$Editor" ~/.manl/"${1}_"

	tmpmd5=$(md5sum /tmp/"${1}_" | awk '{ print $1 }')
	manlmd5=$(md5sum ~/.manl/"${1}_" | awk '{ print $1 }')
	# echo "tmp  ${tmpmd5}"
	# echo "manl ${manlmd5}"
fi

if	[[ -z ${2} ]] && [[ ${tmpmd5} != "${manlmd5}" ]]; then
	echo; echo "New notes saved as ~/.manl/${1}"

		if	[[ -e  ~/.manl/"${1}" ]]; then
			mv ~/.manl/"${1}" ~/.manl/"${1}.bu"
			echo; echo "Pre-edited notes saved as ~/.manl/${1}_${2}.bu" ; echo
		fi

	cp ~/.manl/"${1}_"  ~/.manl/"${1}"
	rm ~/.manl/"${1}_"
	rm /tmp/"${1}_"

	del=$(echo "${1}" | tr '[:lower:]' '[:upper:]')
	sed '/'"$del"'/,$d' ~/.manl/"${1}" > ~/.manl/"${1}".tmp
	mv ~/.manl/"${1}".tmp  ~/.manl/"${1}"
    elif
	[[ -z ${2} ]]; then
	rm ~/.manl/"${1}_"
	rm /tmp/"${1}_"
fi

